services:
  _defaults:
    autowire: true
    autoconfigure: true

  Lifo\AutocompleteBundle\Form\Type\Select2Type:
    tags: [ { name: form.type } ]

  Lifo\AutocompleteBundle\Form\Type\MultiselectType:
    tags: [ { name: form.type } ]

